######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 5 11:21:30 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h pieview.h qcustomplot.h
SOURCES += main.cpp mainwindow.cpp pieview.cpp qcustomplot.cpp
RESOURCES += chart.qrc
